cloudcounter/Controllers/CounterAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CloudCounter.Domain.Interface;
using CloudCounter.Domain.IoC;
using CloudCounter.Domain.Model;
using StructureMap;

namespace cloudcounter.Controllers
{
    public class CounterAdminController : Controller
    {
        private ICloudCounterRepository _repository;

        [DefaultConstructor]
        public CounterAdminController()
        {
            _repository = IoCContainer.GetInstance<ICloudCounterRepository>();
        }



        public ActionResult List (int accountid=902)
        {

            ViewData.Model = _repository.GetCounters(accountid);
            return View ("~/Views/CounterAdmin/List.cshtml");
        }
    }
}

cloudcounter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cloudcounter.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

cloudcounter/Views/Home/Index.cshtml
    <header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">
                <a href="~/">ASP.NET Web API</a></p>
        </div>
    </div>
</header>
<div id="body">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Welcome to Cloud Counter</h1>
                <h2></h2>
            </hgroup>
            <p>
              Cloud Counter allows you to spin up easy to you simple counters in the cloud
            </p>
            <p>
              
            </p>
        </div>
    </section>
    <section class="content-wrapper main-content clear-fix">
        <h3>We suggest the following steps:</h3>
        <ol class="round">
            <li class="one">
                <h5>Getting Started</h5>
                @Html.ActionLink("Counter List", "List", "CounterAdmin")                
                ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
                a broad range of clients, including browsers and mobile devices. ASP.NET Web API
                is an ideal platform for building RESTful applications on the .NET Framework.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245160">Learn more…</a>
            </li>

            <li class="two">
                <h5>Add NuGet packages and jump-start your coding</h5>
                NuGet makes it easy to install and update free libraries and tools.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245161">Learn more…</a>
            </li>
            <li class="three">
                <h5>Find Web Hosting</h5>
                You can easily find a web hosting company that offers the right mix of features
                and price for your applications.
                <a href="http://go.microsoft.com/fwlink/?LinkId=245164">Learn more…</a>
            </li>
        </ol>
    </section>
</div>